variation-map: &variation-map
  dimensions: 2
  type: CELLULAR
  return: CellValue
  frequency: 1 / ${meta.yml:biome-distribution.variation-scale} / ${meta.yml:biome-distribution.global-scale}

stages:
  - type: REPLACE
    from: coast
    to:
      - SNOWDRIFT_COASTS: 1
    sampler: *variation-map